### ISSUE TITLE
Error de sql

### ISSUE THREAD

**Issue by 8tnc** [decode2/Zombie-Survival#1]
Hello, I wanted to know if you could help me since it does not let me import the sql and when I enter the server the user does not register me 
![image](https://user-images.githubusercontent.com/78674116/177632049-f6558143-0782-4d01-a5fe-c25acb13918e.png)
![image](https://user-images.githubusercontent.com/78674116/177632099-5db1114c-a349-4ba1-81cb-85e24bda7b8f.png)
L 07/06/2022 - 17:00:51: [zombie_survival.smx] SELECT P.steamid, P.contrasenia, P.email, P.blockAccess, P.piupoints FROM players P WHERE P.steamid=892828951

L 07/06/2022 - 17:01:17: [zombie_survival.smx] [REGISTER] error: Unknown column 'steamid' in 'field list'

**Comment by decode2** [comment]
It's not a problem in the code, you need SUPER privileges in your database for the file to create the needed procedures

**Comment by 8tnc** [comment]
Isn't there a way to do it without those permissions? since for me it is not possible to have them

**Comment by decode2** [comment]
Creating the procedure manually
