### ISSUE TITLE
Un poco mas de info

### ISSUE THREAD

**Issue by Ic3dM4n** [decode2/Zombie-Survival#3]
Hola bro, vi que eres argentino, entonces creo que no vaya haber problema que te escriba en español :D.
Bien, me interesa el mod tuyo, lo estuve testeando en un dedicado.
Use:
* mysql workbech 8.0 CE
* Sourcemod 1.11
* Metamod 1.11
* PTAH ultima version

y aun hay problema con la base de datos con el .sql que esta en tu archivo.
Con un amigo estuvimos ahí modificando un poco y logramos que no tire error en la consola con la base de datos.
Cuando entro al dedicado aparece el menú de entrar a jugar, pero dice que el usuario no puede registrarse y ahí comienza de nuevo el problema de la base de datos, que dicho usuario no puede crear una cuenta.

Podrías fijarte si te corre a vos, calculo que después de meses, algo cambio y por eso no funciona.

Otra duda. Se puede usar el PHPMYADMIN?

**Comment by decode2** [comment]
Buenas tardes, puede ser por un problema con el engine que estés usando para la DB, sí es posible usar phpmyAdmin, pero es necesario verificar que la tipificación de la DB sea según el plugin solicita (si mal no recuerdo utf8mb4)

Para diagnositcar mejor, necesitaría ver logs al respecto

**Comment by Ic3dM4n** [comment]
Recibo este error cuando cargo zombie_survival.sql

![Screenshot_2](https://github.com/decode2/Zombie-Survival/assets/31681229/c923f644-1aba-4a7c-a44d-166f39f916fa)

y por las dudas, si llega a pasar esto

![Screenshot_1](https://github.com/decode2/Zombie-Survival/assets/31681229/ba8f670a-7b1a-4c05-9f80-0222f4bce1d2)

que debo hacer?

**Comment by decode2** [comment]
Eso es primordial que corra, sino vas a tener problemas con la creación de stored procedures.
Podrías consultar a tu hosting si pueden darte el permiso de admin de phpmyAdmin o correr esa linea

**Comment by Ic3dM4n** [comment]
Mala noticias. Acá me dieron la respuesta :C

El tema es que eso nos va a generar un impacto en el servidor mysql en general.
es muy raro lo te esta solicitando el programador, o bien es algo muy único que tienes que correr en un mysql propio.

**Comment by decode2** [comment]
En realidad, eso permite que crees stored procedures, lo que se encargaría de crear funciones de SQL para el sistema de guardados.

Podrías sino, pedirles que te creen tus procedimientos.

Por otro lado, tendrás logs de los errores que da al registrar un personaje? Quizás hay otra forma de solucionarlo.

**Comment by Ic3dM4n** [comment]
Podría usar mysql workbech 8.0 CE, pero necesitaría una demostración. Porque mucha experiencia con ese programa no tengo :C

**Comment by Ic3dM4n** [comment]
L 05/19/2023 - 01:58:04: [zombie_survival.smx] SELECT P.steamid, P.contrasenia, P.email, P.blockAccess, P.piupoints FROM players P WHERE P.steamid=102330778
L 05/19/2023 - 02:01:31: [zombie_survival.smx] SELECT P.steamid, P.contrasenia, P.email, P.blockAccess, P.piupoints FROM players P WHERE P.steamid=102330778
L 05/19/2023 - 02:01:31: [zombie_survival.smx] Login playerCallback OK
L 05/19/2023 - 02:01:31: [zombie_survival.smx] SELECT c.id, c.nombre, c.level, c.reset, c.accesslevel FROM players p RIGHT JOIN Characters c ON (p.id = c.idPlayer) WHERE p.steamid = 102330778
L 05/19/2023 - 02:07:37: [zombie_survival.smx] SELECT P.steamid, P.contrasenia, P.email, P.blockAccess, P.piupoints FROM players P WHERE P.steamid=102330778
L 05/19/2023 - 02:07:37: [zombie_survival.smx] Login playerCallback OK
L 05/19/2023 - 02:07:37: [zombie_survival.smx] SELECT c.id, c.nombre, c.level, c.reset, c.accesslevel FROM players p RIGHT JOIN Characters c ON (p.id = c.idPlayer) WHERE p.steamid = 102330778


L 05/19/2023 - 02:07:42: Info (map "zm_bunker") (file "E:\steamcmd\ZombiePlague\csgo\addons\sourcemod\logs\errors_20230519.log")
L 05/19/2023 - 02:07:42: [zombie_survival.smx] [Create-Character] user icedman is trying create character, error: The user specified as a definer ('zombie_survival'@'%') does not exist
L 05/19/2023 - 02:08:14: [zombie_survival.smx] [Create-Character] user icedman is trying create character, error: The user specified as a definer ('zombie_survival'@'%') does not exist


![Screenshot_1](https://github.com/decode2/Zombie-Survival/assets/31681229/a454d047-56c2-4840-bf82-beacb37d9147)


Esto es lo que pude ver de error.

Te pido mil disculpas por molestar con tantos mensajes.

**Comment by decode2** [comment]
No está detectando cuál es tu usuario de base de datos, configuraste correctamente el databases.cfg?

**Comment by Ic3dM4n** [comment]
![Screenshot_1](https://github.com/decode2/Zombie-Survival/assets/31681229/ad8141d4-bdd4-448f-8c58-9253b1935e5a)
![Screenshot_2](https://github.com/decode2/Zombie-Survival/assets/31681229/01fe7ab1-680f-4330-816e-8ad4f1d653ee)
![Screenshot_3](https://github.com/decode2/Zombie-Survival/assets/31681229/526ce7eb-4d6f-4e29-b274-c6ede1b965bc)
![Screenshot_4](https://github.com/decode2/Zombie-Survival/assets/31681229/ff6fd54f-b993-43d1-a150-0fbcb01dcccf)

**Comment by decode2** [comment]
Dentro de los stored procedures.. qué dice? Deberían estar asociados a tu usuario y database.

**Comment by Ic3dM4n** [comment]
Me podrias agregar a discord?
Asi lo hacemos de una jajajaj
Si no quieres, no hay problema, lo entiendo.
Ic3dM4n#9336

**Comment by decode2** [comment]
No tengo problema, pero preferiría que quede documentado acá por si otra persona tiene el mismo problema

**Comment by Ic3dM4n** [comment]
Si, claro. Si logro que funcione dejo todo lo que modificamos acá. No tengo ningún problema.

**Comment by Ic3dM4n** [comment]
Bueno, instale todo de nuevo y me tira el siguiente error:
![Screenshot_2](https://github.com/decode2/Zombie-Survival/assets/31681229/88e57181-ed52-4542-994b-a82c3d1333a6)

**Comment by Ic3dM4n** [comment]
Agregando el siguiente comando al MySQL me soluciono el problema y ahora si funciona el mod

ALTER USER 'tuusuario'@'localhost' IDENTIFIED WITH mysql_native_password BY 'tucontraseña';

Recuerda reemplzar "tuusuario" y "tucontraseña" con los datos de tu root y localhost.

y por ultimo refrescar la Schema. Ejecutas el server y a entrar. PD: Necesitas configurar el mod ya a tu gusto.
